"""added table for govermentHolyday

Revision ID: 95f0ad3088b7
Revises: 4e2fa3efe754
Create Date: 2026-09-18 16:53:36.593601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f0ad3088b7'
down_revision: Union[str, Sequence[str], None] = '4e2fa3efe754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
