import logging
from app.agent.llm import get_llm

logger = logging.getLogger(__name__)
llm = get_llm()


def format_answer(state):
    print("--- ENTERING NODE: format_answer ---")

    # -------------------------------------------------------
    # FAST PATH: If validate_sql set an access-denied message
    # (validation_result == "unauthorized"), return it directly
    # without calling the LLM — the message is already polished.
    # -------------------------------------------------------
    if state.get("validation_result") == "unauthorized":
        return {"final_answer": state.get("final_answer", "Access denied.")}

    # -------------------------------------------------------
    # FAST PATH: If the DB result itself is an ACCESS DENIED
    # sentinel (generated by the LLM per ACCESS CONTROL POLICY)
    # surface it cleanly without reformatting.
    # -------------------------------------------------------
    query_result = state.get("query_result", "") or ""
    if "ACCESS DENIED" in str(query_result).upper():
        return {
            "final_answer": (
                "🚫 **Access Denied**\n\n"
                "You do not have permission to view another employee's personal data, "
                "leave details, or salary information.\n\n"
                "Only **HR** and **Managers** can access other employees' information."
            )
        }

    user_role = state.get("role", "EMPLOYEE")
    user_id   = state.get("user_id", "")

    prompt = f"""
User Question:

{state.get("question")}

SQL Query Generated:

{state.get("sql_query", "None")}

Database Result:

{query_result or "None"}

Error (if any):

{state.get("error", "None")}

Current User Role: {user_role}
Current User ID  : {user_id}

Give a highly natural, conversational, and helpful answer to the user based on the database result.
If the database result contains multiple rows or columns, summarize the information in plain English sentences (e.g. "We have 2 clients: Apple and Microsoft") rather than dumping the raw data.
CRITICAL: Do NOT output markdown tables, raw database rows, or technical IDs. Present the data seamlessly in a conversational way.

If there was an error generating or running the query, or if the question is unrelated to the database, answer the user conversationally and gracefully (e.g. "I'm sorry, I don't have access to that information in the database right now.").

VERY IMPORTANT SCOPE RESTRICTION:
You are strictly an AI assistant for an Employee Management system. 
If the user asks a general knowledge question, coding question, or anything completely unrelated to employee management (e.g., "what is python", "write a poem", "what is the weather"), you MUST outright refuse to answer it. 
Instead, reply exactly or similarly to: "I am an AI assistant specifically for employee management. I cannot answer general knowledge questions." Do not answer the question under any circumstances.

PRIVACY REMINDER:
If the database result contains data that appears to belong to another employee and the current user role is 'EMPLOYEE', do NOT surface it. Instead respond: "You do not have permission to view that information."

Do not mention unnecessary technical details, SQL queries, or internal errors.
Speak directly to the user as a helpful AI assistant.
"""

    response = llm.invoke(prompt)

    return {
        "final_answer": response.content
    }